### ISSUE TITLE
Issue generating QR code with long string

### ISSUE THREAD

**Issue by tiny2tom** [dementeddevil/BarcodeRenderingFramework#8]
I am getting the following error when trying to pass strings of character length 123 or above. The QR is rendered fine otherwise.

Index was outside the bounds of the array.
   at Zen.Barcode.CodeQrBarcodeDraw.QRCodeEncoder.divideDataBy8Bits(Int32[] data, SByte[] bits, Int32 maxDataCodewords)
   at Zen.Barcode.CodeQrBarcodeDraw.QRCodeEncoder.CalculateQrCode(Byte[] qrcodeData)
   at Zen.Barcode.CodeQrBarcodeDraw.QRCodeEncoder.Encode(String content, Encoding encoding)
   at Zen.Barcode.CodeQrBarcodeDraw.QRCodeEncoder.Encode(String content)
   at Zen.Barcode.CodeQrBarcodeDraw.DrawQr(String text, BarcodeMetricsQr metrics)
   at Zen.Barcode.CodeQrBarcodeDraw.Draw(String text, BarcodeMetrics metrics)

**Comment by edmaarcosta** [comment]
Any update?
